name: CD to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '--testcd')"
    steps:
    - uses: actions/checkout@v2
    - name: gcr.io/cloud-builders/docker
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcloud.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud config set project $PROJECT_ID
        gcloud builds submit --config cloud-build.yaml .
